# Generated by Django 4.2.11 on 2026-02-27 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("site_name", models.CharField(default="CargoPro", max_length=255)),
                ("contact_email", models.EmailField(blank=True, max_length=254)),
                ("timezone", models.CharField(default="UTC", max_length=100)),
                ("currency", models.CharField(default="USD", max_length=10)),
                ("logo", models.ImageField(blank=True, null=True, upload_to="logos/")),
                ("email_alerts_enabled", models.BooleanField(default=False)),
                ("sms_alerts_enabled", models.BooleanField(default=False)),
                ("session_timeout_minutes", models.PositiveIntegerField(default=60)),
                ("two_factor_enabled", models.BooleanField(default=False)),
                ("api_key", models.CharField(blank=True, max_length=255)),
                ("webhook_url", models.URLField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "System Settings",
                "verbose_name_plural": "System Settings",
            },
        ),
    ]
