# Generated by Django 5.1.7 on 2025-04-11 11:07

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shipments", "0002_alter_user_options_alter_user_managers_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Staff",
            fields=[],
            options={"proxy": True, "indexes": [], "constraints": [],},
            bases=("shipments.user",),
            managers=[("objects", django.contrib.auth.models.UserManager()),],
        ),
    ]
