# Generated by Django 4.2.11 on 2026-02-27 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipments", "0002_step"),
    ]

    operations = [
        migrations.CreateModel(
            name="Parameter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("vessel", "Vessels & Shipping Lines"),
                            ("parcel_status", "Parcel Status"),
                            ("transport", "Means of Transport"),
                            ("commodity", "Commodity Types"),
                            ("payment", "Payment Methods"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("color", models.CharField(blank=True, default="", max_length=7)),
                ("is_default", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["category", "sort_order", "name"],
                "unique_together": {("category", "name")},
            },
        ),
    ]
