# Generated by Django 5.1.7 on 2025-04-12 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shipments", "0003_staff"),
    ]

    operations = [
        migrations.DeleteModel(name="Staff",),
    ]
