# Generated by Django 5.1.7 on 2025-06-20 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipments", "0004_delete_staff"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parcel",
            name="commodity_type",
            field=models.CharField(
                choices=[
                    ("Box", "Box"),
                    ("parcel", "Parcel"),
                    ("envelope", "Envelope"),
                ],
                default="parcel",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="shipment",
            name="status",
            field=models.CharField(
                choices=[("In_transit", "In-transit"), ("Delivered", "Delivered")],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="shipment",
            name="transport",
            field=models.CharField(
                choices=[
                    ("Air", "Air"),
                    ("Sea", "Sea"),
                    ("Road", "Road"),
                    ("Rail", "Rail"),
                ],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("Customer", "Customer"),
                    ("Staff", "Staff"),
                    ("Admin", "Admin"),
                ],
                default="customer",
                max_length=10,
            ),
        ),
    ]
