# Generated by Django 5.1.7 on 2025-06-21 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "shipments",
            "0005_alter_parcel_commodity_type_alter_shipment_status_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="document_type",
            field=models.CharField(
                choices=[
                    ("Invoice", "Invoice"),
                    ("Bill_of_lading", "Bill of Lading"),
                    ("Customs_clearance", "Customs Clearance"),
                    ("Packing_list", "Packing List"),
                    ("Other", "Other"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="status",
            field=models.CharField(
                choices=[
                    ("Unpaid", "Unpaid"),
                    ("Paid", "Paid"),
                    ("Overdue", "Overdue"),
                ],
                default="Unpaid",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="parcel",
            name="commodity_type",
            field=models.CharField(
                choices=[
                    ("Box", "Box"),
                    ("Parcel", "Parcel"),
                    ("Envelope", "Envelope"),
                ],
                default="parcel",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="shipment",
            name="status",
            field=models.CharField(
                choices=[("In-transit", "In-transit"), ("Delivered", "Delivered")],
                max_length=20,
            ),
        ),
    ]
