# Generated by Django 5.1.7 on 2025-06-21 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "shipments",
            "0006_alter_document_document_type_alter_invoice_status_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="status",
            field=models.CharField(
                choices=[("Active", "Active"), ("Domant", "Domant")],
                default="Active",
                max_length=20,
            ),
        ),
    ]
