# Generated by Django 5.1.7 on 2025-06-21 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipments", "0007_customer_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="status",
            field=models.CharField(
                choices=[("Active", "Active"), ("Dormant", "Dormant")],
                default="Active",
                max_length=20,
            ),
        ),
    ]
