# Generated by Django 5.1.7 on 2025-06-21 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipments", "0008_alter_customer_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Paid", "Paid"),
                    ("Overdue", "Overdue"),
                ],
                default="Pending",
                max_length=20,
            ),
        ),
    ]
