# Generated by Django 5.1.7 on 2025-06-27 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipments", "0009_alter_invoice_status"),
    ]

    operations = [
        migrations.RemoveField(model_name="customer", name="shipment",),
        migrations.RemoveField(model_name="invoice", name="parcel",),
        migrations.RemoveField(model_name="invoice", name="shipment",),
        migrations.AddField(
            model_name="shipment",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shipments",
                to="shipments.customer",
            ),
        ),
    ]
