# Generated by Django 5.1.7 on 2025-06-27 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shipments", "0010_remove_customer_shipment_remove_invoice_parcel_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="shipment", name="customer",),
    ]
