# Generated by Django 5.1.7 on 2025-06-27 21:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipments", "0011_remove_shipment_customer"),
    ]

    operations = [
        migrations.AddField(
            model_name="shipment",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shipments",
                to="shipments.customer",
            ),
        ),
    ]
