# Generated by Django 5.1.7 on 2025-06-27 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shipments", "0012_shipment_customer"),
    ]

    operations = [
        migrations.RemoveField(model_name="shipment", name="customer",),
    ]
