# Generated by Django 5.1.7 on 2025-06-29 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipments", "0013_remove_shipment_customer"),
    ]

    operations = [
        migrations.RemoveField(model_name="parcel", name="payment_currency",),
        migrations.AlterField(
            model_name="parcel",
            name="payment",
            field=models.CharField(
                choices=[("Paid", "Paid"), ("Unpaid", "Unpaid")],
                default="Unpaid",
                max_length=20,
            ),
        ),
    ]
