# Generated by Django 5.1.7 on 2025-07-07 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipments", "0014_remove_parcel_payment_currency_alter_parcel_payment"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="parcel",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invoices",
                to="shipments.parcel",
            ),
        ),
    ]
