# Generated by Django 5.1.7 on 2025-08-12 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipments", "0015_invoice_parcel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("customer", "Customer"),
                    ("staff", "Staff"),
                    ("admin", "Admin"),
                ],
                default="customer",
                max_length=10,
            ),
        ),
    ]
