# Generated by Django 5.1.7 on 2025-08-12 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipments", "0016_alter_user_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shipment",
            name="status",
            field=models.CharField(
                choices=[
                    ("In-transit", "In-transit"),
                    ("Delivered", "Delivered"),
                    ("Not-boarded", "Not-boarded"),
                ],
                max_length=20,
            ),
        ),
    ]
