# Generated by Django 5.1.7 on 2025-08-12 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipments", "0017_alter_shipment_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="parcel",
            name="status",
            field=models.CharField(default="Pending", max_length=50),
        ),
    ]
