# Generated by Django 5.1.7 on 2025-08-15 00:32

import djmoney.models.fields
from decimal import Decimal
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shipments", "0019_remove_invoice_parcel_invoiceitem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="final_amount",
            field=djmoney.models.fields.MoneyField(
                decimal_places=2,
                default=Decimal("0"),
                default_currency="TZS",
                max_digits=14,
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="total_amount",
            field=djmoney.models.fields.MoneyField(
                decimal_places=2,
                default=Decimal("0"),
                default_currency="TZS",
                max_digits=14,
            ),
        ),
    ]
